"""
Report generation - wraps legacy Excel and Word report functions.
"""
import shutil
from datetime import datetime
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Dict, Any

from app.audit import legacy_functions


def generate_excel_report(all_results: Dict[str, Any], output_dir: Path,
                          client_name: str, site_name: str, serial_number: str,
                          license_end_date: str, system_uptime: str,
                          regle_no_match: int) -> Path:
    """
    Generate Excel report using legacy function.
    Returns path to generated file.
    """
    creer_rapport_excel = legacy_functions.creer_rapport_excel

    # Extract all parameters in the exact order expected by legacy function
    filename = creer_rapport_excel(
        all_results["guest_result"],
        all_results["guest_conform"],
        all_results["admin_result"],
        all_results["admin_conform"],
        all_results["usb_result"],
        all_results["usb_conform"],
        all_results["vs_any_result"],
        all_results["vs_any_conform"],
        all_results["vip_any_result"],
        all_results["vip_any_conform"],
        all_results["utilisation_ssl_result"],
        all_results["utilisation_ssl_conform"],
        all_results["all_in_rules_result"],
        all_results["all_in_rules_conform"],
        all_results["all_in_rules_ids"],
        all_results["geo_ip_result"],
        all_results["geo_ip_conform"],
        all_results["hostname"],
        all_results["version_fortigate_result"],
        all_results["version_conform"],
        all_results["isdb_result"],
        all_results["isdb_conform"],
        all_results["version_cve_message"],
        all_results["http_https_result"],
        all_results["eol_result"],
        all_results.get("eol_conform", False) if all_results.get("eol_conform") is not None else False,
        all_results["http_https_conform"],
        all_results["http_https_enabled_interfaces"],
        all_results["interfaces_access_details"],
        all_results["admin_sns_result"],
        all_results["admin_sns_conform"],
        all_results["pki_sns_result"],
        all_results["pki_sns_conform"],
        all_results["pki_pkisns_result"],
        all_results["pki_pkisns_conform"],
        all_results["deny_implicit_result"],
        all_results["deny_implicit_conform"],
        all_results["sync_fortianalyzer_result"],
        all_results["sync_fortianalyzer_conform"],
        all_results["sync_fortimanager_result"],
        all_results["sync_fortimanager_conform"],
        all_results["mfa_result"],
        all_results["mfa_conform"],
        all_results["ike_result"],
        all_results["ike_conform"],
        all_results["ike_list"],
        all_results["dh_result"],
        all_results["dh_conform"],
        all_results["dh_list"],
        all_results["algo_result"],
        all_results["algo_conform"],
        all_results["algo_list"],
        all_results["cti_result"],
        all_results["cti_conform"],
        all_results["ldaps_result"],
        all_results["ldaps_conform"],
        all_results["sauvegardes_result"],
        all_results["sauvegardes_conform"],
        all_results["objets_result"],
        all_results["objets_conform"],
        all_results["objets_non_utilises"],
        all_results["acces_admin_sns_result"],
        all_results["acces_admin_sns_conform"],
        all_results["dns_database_result"],
        all_results["dns_database_conform"],
        all_results["sip_alg_result"],
        all_results["sip_alg_conform"],
        all_results["fortisandbox_result"],
        all_results["fortisandbox_conform"],
        all_results["anycast_fortiguard_result"],
        all_results["anycast_fortiguard_conform"],
        all_results["fortiguard_result"],
        all_results["fortiguard_conform"],
        all_results["blackhole_result"],
        all_results["blackhole_conform"],
        all_results["ha_session_pickup_result"],
        all_results["ha_session_pickup_conform"],
        all_results["ha_cablage_result"],
        all_results["ha_cablage_conform"],
        all_results["ha_redundance_result"],
        all_results["ha_redundance_conform"],
        all_results["ha_override_result"],
        all_results["ha_override_conform"],
        all_results["ports_deny_result"],
        all_results["ports_deny_conform"],
        all_results["sdwan_result"],
        all_results["sdwan_conform"],
        all_results["sdwan_action_message"],
        all_results["licence_utm"],
        all_results["result_profils"],
        all_results["conformity_profils"],
        all_results["rule_ids_profils"],
        all_results["result_mail_filter"],
        all_results["conformity_mail_filter"],
        all_results["rule_ids_mail_filter"],
        all_results["result_web_filter"],
        all_results["conformity_web_filter"],
        all_results["non_conforming_web_filter"],
        all_results["av_result"],
        all_results["av_conformity"],
        all_results["av_non_conforming"],
        all_results["dnsfilter_result"],
        all_results["dnsfilter_conformity"],
        all_results["dnsfilter_non_conforming"],
        all_results["ips_result"],
        all_results["ips_conformity"],
        all_results["ips_non_conforming"],
        all_results["result_app_control"],
        all_results["conformity_app_control"],
        all_results["non_conforming_app_control"],
        all_results["result_port_https_admin"],
        all_results["is_compliant_https"],
        all_results["modele_FAP_result"],
        all_results["modele_FAP_conform"],
        all_results["modele_FAP_list"],
        all_results["ssid_result"],
        all_results["ssid_conform"],
        all_results["ssid_non_conforming_profiles"],
        all_results["bande_5ghz_result"],
        all_results["bande_5ghz_conform"],
        all_results["bande_5ghz_non_conform"],
        all_results["darrp_result"],
        all_results["darrp_conform"],
        all_results["darrp_non_conform"],
        all_results["frequency_handoff_result"],
        all_results["frequency_handoff_conform"],
        all_results["frequency_handoff_non_conform"],
        all_results["tim_result"],
        all_results["tim_conform"],
        all_results["tim_non_conform"],
        all_results["nb_all"],
        all_results["nb_disabled"],
        all_results["nb_utm"],
        all_results["users_data"],
        all_results["nb_policy_enable"],
        all_results["nb_policy_disabled"],
        all_results["nb_policy_always"],
        all_results["nb_policy_schedule_actif"],
        all_results["nb_policy_schedule_expire"],
        all_results["ssl_ssh_result"],
        all_results["ssl_ssh_conform"],
        all_results["ssl_ssh_non_conforming"],
        all_results["rule_ids_ssl_ssh"],
        all_results["version"],
        all_results["model"],
        all_results["band_result"],
        all_results["band_conform"],
        all_results["band_non_conform"],
        all_results["channel_result"],
        all_results["channel_conform"],
        all_results["channel_non_conform"],
        all_results["sgi_result"],
        all_results["sgi_conform"],
        all_results["sgi_non_conform"],
        all_results["sequence_result"],
        all_results["sequence_conform"],
        regle_no_match=regle_no_match,
        client_name=client_name,
        site_name=site_name,
        serial_number=serial_number,
        license_end_date=license_end_date,
        system_uptime=system_uptime,
    )

    # Move file to output directory if needed.
    # shutil.move, not Path.rename: the legacy generator writes to the working
    # directory, and when reports/ is a mounted volume the two live on different
    # filesystems. rename() would fail there with EXDEV (cross-device link).
    excel_path = Path(filename)
    if output_dir.exists() and excel_path.parent.resolve() != output_dir.resolve():
        new_path = output_dir / excel_path.name
        shutil.move(str(excel_path), str(new_path))
        return new_path
    return excel_path


def generate_word_report(all_results: Dict[str, Any], output_dir: Path,client_name: str, serial_number: str) -> Path:
    """
    Generate Word report using legacy function.
    Returns path to generated file.
    """
    creer_rapport_word = legacy_functions.creer_rapport_word

    filename = creer_rapport_word(
        all_results["hostname"],
        all_results["version"],
        all_results["model"],
        all_results["config_lines"],
        all_results["version_conform"],
        all_results.get("eol_conform", False),
        all_results["sauvegardes_conform"],
        all_results["usb_conform"],
        all_results["result_port_https_admin"],
        all_results["is_compliant_https"],
        all_results["sync_fortimanager_result"],
        all_results["sync_fortimanager_conform"],
        all_results["sync_fortianalyzer_result"],
        all_results["sync_fortianalyzer_conform"],
        all_results["http_https_result"],
        all_results["http_https_conform"],
        all_results["admin_result"],
        all_results["admin_conform"],
        all_results["mfa_result"],
        all_results["mfa_conform"],
        all_results["deny_implicit_result"],
        all_results["deny_implicit_conform"],
        all_results["sdwan_result"],
        all_results["sdwan_conform"],
        all_results["isdb_result"],
        all_results["isdb_conform"],
        all_results["cti_result"],
        all_results["cti_conform"],
        all_results["all_in_rules_result"],
        all_results["all_in_rules_conform"],
        all_results["vip_any_result"],
        all_results["vip_any_conform"],
        all_results["vs_any_result"],
        all_results["vs_any_conform"],
        all_results["geo_ip_result"],
        all_results["geo_ip_conform"],
        all_results["ldaps_result"],
        all_results["ldaps_conform"],
        all_results["ha_session_pickup_result"],
        all_results["ha_session_pickup_conform"],
        all_results["ha_cablage_result"],
        all_results["ha_cablage_conform"],
        all_results["ha_redundance_result"],
        all_results["ha_redundance_conform"],
        all_results["ha_override_result"],
        all_results["ha_override_conform"],
        all_results["utilisation_ssl_result"],
        all_results["utilisation_ssl_conform"],
        all_results["ike_result"],
        all_results["ike_conform"],
        all_results["dh_result"],
        all_results["dh_conform"],
        all_results["algo_result"],
        all_results["algo_conform"],
        all_results["licence_utm"],
        all_results["dnsfilter_result"],
        all_results["dnsfilter_conformity"],
        all_results["result_web_filter"],
        all_results["conformity_web_filter"],
        all_results["av_result"],
        all_results["av_conformity"],
        all_results["ips_result"],
        all_results["ips_conformity"],
        all_results["result_app_control"],
        all_results["conformity_app_control"],
        all_results["modele_FAP_result"],
        all_results["modele_FAP_conform"],
        all_results["modele_FAP_list"],
        all_results["ssid_result"],
        all_results["ssid_conform"],
        all_results["ssid_non_conforming_profiles"],
        all_results.get("profiles_utilises", {}),
        all_results["bande_5ghz_result"],
        all_results["bande_5ghz_conform"],
        all_results["bande_5ghz_non_conform"],
        all_results["darrp_result"],
        all_results["darrp_conform"],
        all_results["darrp_non_conform"],
        all_results["frequency_handoff_result"],
        all_results["frequency_handoff_conform"],
        all_results["frequency_handoff_non_conform"],
        all_results["tim_result"],
        all_results["tim_conform"],
        all_results["tim_non_conform"],
        all_results["band_result"],
        all_results["band_conform"],
        all_results["band_non_conform"],
        all_results["channel_result"],
        all_results["channel_conform"],
        all_results["channel_non_conform"],
        all_results["sgi_result"],
        all_results["sgi_conform"],
        all_results["sgi_non_conform"],
        all_results["objets_result"],
        all_results["objets_conform"],
        all_results["objets_non_utilises"],
        all_results["result_profils"],
        all_results["conformity_profils"],
        all_results["rule_ids_profils"],
        all_results["blackhole_result"],
        all_results["blackhole_conform"],
        all_results["ports_deny_result"],
        all_results["ports_deny_conform"],
        all_results["fortiguard_result"],
        all_results["fortiguard_conform"],
        all_results["fortisandbox_result"],
        all_results["fortisandbox_conform"],
        all_results["sequence_result"],
        all_results["sequence_conform"],
        client_name=client_name,
        serial_number=serial_number,
    )

    # Move file to output directory if needed.
    # shutil.move, not Path.rename: the legacy generator writes to the working
    # directory, and when reports/ is a mounted volume the two live on different
    # filesystems. rename() would fail there with EXDEV (cross-device link).
    word_path = Path(filename)
    if output_dir.exists() and word_path.parent.resolve() != output_dir.resolve():
        new_path = output_dir / word_path.name
        shutil.move(str(word_path), str(new_path))
        return new_path
    return word_path


def write_summary_report(summary: Dict[str, Any]) -> Path:
    """Write a simple JSON summary report (legacy compatibility)."""
    from json import dumps
    tmp = NamedTemporaryFile(mode='w', delete=False, suffix='.json', encoding='utf-8')
    tmp.write(dumps(summary, indent=2, ensure_ascii=False))
    tmp.flush()
    return Path(tmp.name)
